server:
  port: 8001
spring:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:productDb;DB_CLOSE_DELAY=-1
    username: sa
    password: null
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        ddl-auto: create-drop
  application:
    name: manageCurrencyms

eureka:
  instance:
    instanceId: ${spring.application.name}:${random.int}
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 5
    preferIpAddress: true
    metadata-map:
      zone: A
  client:
    registerWithEureka: true
    fetchRegistry: true
    prefer-same-zone-eureka: true
    serviceUrl:
      defaultZone: ${manageCurrencyms.eureka.url:http://localhost:8761/eureka}

feign:
  hystrix:
    enabled: true   
        

management:
  endpoints:
    web:
      exposure:
        include: '*'